name: Release

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com/'
      - name: Generate metafiles
        uses: rouvydev/metagen-gha@v1.4
        with:
          seed: 'uSJ7s93wNn7MF1NovhPoOVwkgpfq21GW'
          directory: ./rouvy.nodatime.unity
      - name: publish
        working-directory: ./rouvy.nodatime.unity
        run: npm publish --registry='https://npm.pkg.github.com/@rouvydev'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}